[tool.poetry]
name = "tumorevo"
version = "0.0.1"
description = "Simulate tumor evolution under different spatial constraints."
license = "MIT"
authors = ["pedrofale <pedro.miguel.ferreira.pf@gmail.com>"]
readme = "README.md"
repository = "https://github.com/pedrofale/tumorevo"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
pandas = "^1.3.2"
numpy = "^1.21.2"
pymuller = "^0.1.2"

[tool.poetry.dev-dependencies]
bump2version = "^1.0.1"
black = "^21.7b0"
pytest = "^6.2.4"

[tool.poetry.scripts]
tumorevo = "tumorevo:main"
